source 'http://rubygems.org'
gem 'bundler', '0.9.20'
gem 'rails', '3.0.0.beta3'
gem 'mongo', '1.0.0'
gem 'bson', '1.0.0'
gem 'bson_ext', '1.0.0'
gem 'mongo_mapper'
gem 'jnunemaker-validatable'
gem 'formtastic'
gem 'haml'
gem 'compass'
gem 'inherited_resources'
gem 'has_scope'
gem 'responders'
gem 'will_paginate'
