# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mongo
  host: flame.mongohq.com
  port: 27045
  database: deck-me-dev
  username: dev
  password: dev