defaults: &defaults
  host: flame.mongohq.com
  port: 27045
  database: deck-me-dev
  username: dev
  password: dev
  allow_dynamic_fields: true
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: false

development:
  <<: *defaults
  database: deck-me-dev

test:
  <<: *defaults
  database: control_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: 
  port: 
  database: 
