defaults: &defaults
  host: flame.mongohq.com
  port: 27045
  allow_dynamic_fields: true
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: false

development:
  <<: *defaults
  database: deck-me-dev
  username: dev
  password: dev

test:
  <<: *defaults
  database: control_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: ENV['MONGOID_HOST']
  port: ENV['MONGOID_PORT']
  username: ENV['MONGOID_USERNAME']
  password: ENV['MONGOID_PASSWORD']
  database: ENV['MONGOID_DATABASE']
