#mongo flame.mongohq.com:27045/deck-me-dev -u <user> -p <pass>
defaults: &defaults
  host: flame.mongohq.com
  port: 27045
  username: dev
  password: dev
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: deck-me-dev

test:
  <<: *defaults
  database: cards_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>